import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createWorldState} from '../supabase/functions/_shared/worldState';
import {applyServerCommand} from '../supabase/functions/_shared/serverCommand';
import {attackRatio,runStrategicAI,strategicContext,warDecisionScore} from '../supabase/functions/_shared/aiSystem';
import {declareWar,diplomaticLink} from '../supabase/functions/_shared/diplomacySystem';
import {normalizeGameState} from '../supabase/functions/_shared/stateMigrations';
function world(){const s=createWorldState('aiqa','AIQA01','host','QA',44);s.phase='running';s.players[0]!.countryId='usa';return s;}
function only(s:ReturnType<typeof world>,id:string){s.players=Object.keys(s.countries).filter(c=>c!==id).map((countryId,i)=>({id:'p'+i,countryId,displayName:'QA',ready:true,isHost:i===0}));s.tick=Object.keys(s.countries).sort().indexOf(id)%6;}
const noop={recruit:()=>{},move:()=>{}};
test('AI war score respects truce, relative power and personality',()=>{const s=world(),c=s.countries.germany!;c.army=1e6;c.treasury=1e6;const context=strategicContext(s,c.id,['france']),leader=s.leaders![c.rulerId!]!;leader.aiPersonality='Expansionist';const expansion=warDecisionScore(s,c.id,'france',context);leader.aiPersonality='Defensive';assert.ok(expansion>warDecisionScore(s,c.id,'france',context));diplomaticLink(s,c.id,'france').truceUntilTick=100;assert.equal(warDecisionScore(s,c.id,'france',context),-Infinity);});
test('AI rejects suicidal attacks including forts and low readiness',()=>{const s=world(),army=s.armies.find(a=>a.ownerId==='germany')!,p=s.provinces.find(p=>p.ownerId==='france')!;army.troops=1000;army.morale=5;army.organization=5;p.buildings={Fort:5};s.armies.push({id:'strong',ownerId:'france',provinceId:p.id,troops:100000,morale:100,organization:100,unitType:'Armor'});assert.ok(attackRatio(s,army,p)<.1);});
test('Economic AI buys research and productive buildings without spending reserve',()=>{const s=world();only(s,'germany');const c=s.countries.germany!;s.leaders![c.rulerId!]!.aiPersonality='Economic';c.treasury=10000;runStrategicAI(s,noop);assert.equal(c.research?.branch,'Economy');assert.ok(s.constructions!.some(q=>q.ownerId===c.id));assert.ok(c.treasury>=strategicContext(s,c.id,[]).treasuryReserve);});
test('Defensive AI builds forts; unprofitable AI cannot repeatedly recruit',()=>{const s=world();only(s,'germany');const c=s.countries.germany!;s.leaders![c.rulerId!]!.aiPersonality='Defensive';c.treasury=10000;let recruits=0;runStrategicAI(s,{...noop,recruit:()=>{recruits++;}});assert.ok(s.constructions!.some(q=>q.ownerId===c.id&&q.buildingType==='Fort'));c.economy!.monthlyBalance=-100;for(let i=0;i<12;i++){s.tick+=6;runStrategicAI(s,{...noop,recruit:()=>{recruits++;}});}assert.ok(recruits<=1);});
test('AI ends a stagnant war and preserves a truce',()=>{const s=world();only(s,'germany');s.players=s.players.filter(p=>p.countryId!=='france');const w=declareWar(s,'germany','france');s.tick+=24;runStrategicAI(s,noop);assert.ok(!s.wars!.some(q=>q.id===w.id));assert.ok(diplomaticLink(s,'germany','france').truceUntilTick>s.tick);});
test('scheduled multi-country AI is deterministic and preserves state invariants across 36 months',()=>{let s=world();const initial=structuredClone(s);for(let i=0;i<36;i++)s=applyServerCommand(s,{type:'ADVANCE_TICK'},'host');normalizeGameState(s);assert.equal(s.tick,36);for(const c of Object.values(s.countries))assert.ok(Number.isFinite(c.treasury)&&c.treasury>=0);assert.ok(Object.values(s.countries).some(c=>Object.values(c.technologies!).some(n=>n>0)));const a=applyServerCommand(initial,{type:'ADVANCE_TICK'},'host'),b=applyServerCommand(initial,{type:'ADVANCE_TICK'},'host');assert.deepEqual(a,b);assert.equal(initial.tick,0);});
test('AI rejects a now-unaffordable peace offer instead of aborting the simulation',()=>{const s=world();only(s,'france');const w=declareWar(s,'germany','france');w.peaceOffer={from:'germany',terms:{kind:'Money',provinceIds:[],amount:1000},expiresTick:s.tick+6};s.countries.france!.treasury=0;assert.doesNotThrow(()=>runStrategicAI(s,noop));assert.equal(w.peaceOffer,undefined);assert.ok(s.wars!.some(x=>x.id===w.id));});
