import {test} from 'node:test';import assert from 'node:assert/strict';
import {createWorldState} from '../supabase/functions/_shared/worldState';
import {CURRENT_STATE_VERSION} from '../supabase/functions/_shared/stateMigrations';
import {decodeCampaign,encodeCampaign,validateCampaign} from '../src/persistence/campaignCodec';
import {CampaignStore,type CampaignFiles} from '../src/persistence/campaignStore';
import {LocalTransport} from '../src/multiplayer/localTransport';
function storage(){const map=new Map<string,string>();const files:CampaignFiles={list:async()=>[...map.keys()],read:async n=>{const value=map.get(n);if(!value)throw Error('missing');return value;},write:async(n,t)=>{map.set(n,t);},move:async(a,b)=>{map.set(b,map.get(a)!);map.delete(a);},remove:async n=>{map.delete(n);}};return{map,files,store:new CampaignStore(files)};}
function world(){const s=createWorldState('saveqa','SAV001','host','QA',32);s.players[0]!.countryId='germany';s.phase='paused';s.speed=0;return s;}
test('save/load/delete and metadata survive new repository and transport instances',async()=>{const{files,store}=storage(),s=world();await store.save(s,'Campaign QA');const restarted=new CampaignStore(files),entry=(await restarted.list())[0]!;assert.equal(entry.metadata!.name,'Campaign QA');assert.equal(entry.metadata!.country,'germany');const loaded=await restarted.load(s.id);assert.deepEqual(loaded,s);const session=await new LocalTransport().restore(loaded);assert.equal(session.playerId,'host');assert.equal(session.state.countries.germany!.treasury,s.countries.germany!.treasury);await restarted.delete(s.id);assert.equal((await restarted.list()).length,0);});
test('old optional state migrates sequentially; invalid ownership and future versions are rejected',()=>{const s=world();s.stateVersion=1;delete s.wars;delete s.diplomacy;delete s.commanders;for(const c of Object.values(s.countries)){delete c.technologies;delete c.warExhaustion;}for(const l of Object.values(s.leaders!))delete l.aiPersonality;const loaded=validateCampaign(s);assert.equal(loaded.stateVersion,CURRENT_STATE_VERSION);assert.equal(loaded.countries.germany!.technologies!.Military,0);assert.ok(loaded.leaders![loaded.countries.germany!.rulerId!]!.aiPersonality);s.provinces[0]!.ownerId='missing';assert.throws(()=>validateCampaign(s));const future=world();future.stateVersion=999;assert.throws(()=>validateCampaign(future));});
test('corrupted latest save reports an error and cannot be overwritten by autosave',async()=>{const{store,map}=storage(),s=world();await store.save(s);const name=[...map.keys()][0]!;map.set(name,'{broken');await assert.rejects(()=>store.load(s.id));await assert.rejects(()=>store.save(s));assert.equal(map.get(name),'{broken');assert.ok((await store.list())[0]!.error);assert.throws(()=>decodeCampaign(encodeCampaign(s,1).replace('"checksum":"','"checksum":"bad')));});
test('interrupted write preserves prior generation; concurrent saves are serialized and bounded',async()=>{const{files,store,map}=storage(),s=world();await store.save(s);const broken=new CampaignStore({...files,move:async()=>{throw Error('disk interrupted');}});s.tick=1;await assert.rejects(()=>broken.save(s));assert.equal((await store.load(s.id)).tick,0);await Promise.all([store.save(s),store.save({...s,tick:2}),store.save({...s,tick:3})]);assert.equal((await store.load(s.id)).tick,3);assert.equal([...map.keys()].filter(n=>n.endsWith('.json')).length,2);});
