import {test} from 'node:test';import assert from 'node:assert/strict';
import {readRequest,assertRoomRequest,MAX_REQUEST_BYTES} from '../supabase/functions/_shared/requestValidation';
import {assertEnvelope} from '../supabase/functions/_shared/sessionState';
import {createWorldState} from '../supabase/functions/_shared/worldState';
import {applyServerCommand} from '../supabase/functions/_shared/serverCommand';
import {assertInvariants} from './helpers/invariants';
const id='11111111-1111-4111-8111-111111111111',token='a'.repeat(43);
const envelope={gameId:id,playerId:id,token,commandId:'security-command',expectedVersion:0,command:{type:'SET_READY',playerId:id,ready:true}};
test('HTTP boundary rejects malformed JSON, primitive roots and streamed oversized bodies',async()=>{for(const body of ['{','null','[]','3','"value"'])await assert.rejects(()=>readRequest(new Request('https://qa',{method:'POST',body})));await assert.rejects(()=>readRequest(new Request('https://qa',{method:'POST',body:' '.repeat(MAX_REQUEST_BYTES+1)})),{status:413});assert.deepEqual(await readRequest(new Request('https://qa',{method:'POST',body:'{"action":"create","displayName":"QA"}'})),{action:'create',displayName:'QA'});});
test('session envelope rejects wrong types, huge credentials, invalid UUID and spoofed state fields',()=>{assert.doesNotThrow(()=>assertEnvelope(envelope));for(const k of ['gameId','playerId','token','commandId','expectedVersion'])for(const value of [null,[],{},-1,'x'.repeat(40000)])assert.throws(()=>assertEnvelope({...envelope,[k]:value}));assert.throws(()=>assertEnvelope({...envelope,treasury:1e9}));for(const body of [{action:'state',gameId:id,playerId:id,token,version:-1},{action:'join',roomCode:{},displayName:'QA'},{action:'create',displayName:'QA',state:{treasury:1e9}}])assert.throws(()=>assertRoomRequest(body));});
test('seeded modern-world command sequences preserve invariants and reject 240 authority spoofs',()=>{let s=createWorldState('fuzz-modern','FUZZ01','host','QA',91);s.players[0]!.countryId='germany';s.phase='paused';s.speed=0;let seed=73,accepted=0,rejected=0;const rng=()=>((seed=Math.imul(seed,1664525)+1013904223|0)>>>0)/4294967296;
 const home=s.provinces.filter(p=>p.ownerId==='germany'),foreign=s.armies.find(a=>a.ownerId==='france')!;
 for(let i=0;i<240;i++){const p=home[Math.floor(rng()*home.length)]!;const options:unknown[]=[{type:'RECRUIT',playerId:'host',provinceId:p.id,troops:1000},{type:'SET_TAX_RATE',playerId:'host',taxRate:10+Math.floor(rng()*11)*5},{type:'BUILD',playerId:'host',provinceId:p.id,buildingType:'Farm'},{type:'START_RESEARCH',playerId:'host',branch:'Economy'},{type:'BORROW',playerId:'host',amount:10},{type:'DIPLOMATIC_ACTION',playerId:'host',targetId:'france',action:'Improve'}];const command=options[i%options.length];const before=JSON.stringify(s);try{s=applyServerCommand(s,command as never,'host');accepted++;}catch{assert.equal(JSON.stringify(s),before);rejected++;}const attack=i%3===0?{type:'MOVE_ARMY',playerId:'host',armyId:foreign.id,provinceId:p.id}:i%3===1?{...(command as object),treasury:1e12}:{...(command as object),playerId:'impostor'};const baseline=JSON.stringify(s);assert.throws(()=>applyServerCommand(s,attack as never,'host'));assert.equal(JSON.stringify(s),baseline);if(i%20===0)assertInvariants(s);}
 assertInvariants(s);assert.ok(accepted>20&&rejected>20);console.log({modernFuzzCommands:240,authoritySpoofs:240,accepted,rejected});});
