import {colors,tokens} from '../ui/tokens';
import {startupTrace} from '../performance/startupTrace';
import {memo,useState,useSyncExternalStore} from 'react';
import {Dimensions,PixelRatio,Platform,Pressable,Share,StyleSheet,Text,View} from 'react-native';
import {getMetrics,metricSamples,subscribeMetrics} from '../performance/telemetry';
import type {FrameRate} from '../performance/quality';
function reportText(){const m=getMetrics(),samples=metricSamples(),mean=(key:'uiFps'|'frameMs')=>samples.length?samples.reduce((n,s)=>n+s[key],0)/samples.length:0;return ['Dominion camera benchmark v4',`Platform: ${Platform.OS} ${Platform.Version}`,`Resolution: ${Dimensions.get('window').width*PixelRatio.get()} × ${Dimensions.get('window').height*PixelRatio.get()}`,`Measured benchmark ticks: ${m.benchmarkTicks}`,`Benchmark error: ${m.benchmarkError||'none'}`,`Preset: ${m.preset}; geometry: ${m.geometryLod}`,`UI callback FPS: ${mean('uiFps').toFixed(1)} (not GPU presentation FPS)`,`UI frame interval: ${mean('frameMs').toFixed(1)}ms`,`Visible provinces/armies/labels: ${m.visibleProvinces}/${m.visibleArmies}/${m.visibleLabels}`,`Rendered geometry features: ${m.renderFeatures}`,`Coverage commits: ${m.cullCommits}; compiled paths: ${m.pathBuilds} / ${m.pathBuildMs.toFixed(1)}ms`,`Retained raster tiles: ${m.rasterTiles}; builds ${m.rasterBuilds} / ${m.rasterMs.toFixed(1)}ms; cache ${(m.rasterBytes/1048576).toFixed(1)} MiB`,`Tap -> action: ${m.tapToActionMs.toFixed(1)}ms; tap -> mounted screen: ${m.tapToScreenMs.toFixed(1)}ms`,`Simulation tick: ${m.simulationMs.toFixed(1)}ms`,`Network round trip: ${m.networkMs.toFixed(1)}ms; response bytes: ${m.networkBytes}`,`Samples: ${samples.length}; rendered map/geography: ${m.mapRenders}/${m.geographyRenders}`,startupTrace(),'GPU frame completion, RAM and thermal state: unavailable through this overlay'].join('\n');}
export const PerformanceOverlay=memo(function PerformanceOverlay(){const m=useSyncExternalStore(subscribeMetrics,getMetrics);return <View pointerEvents="none" accessible accessibilityLabel={"DOMINION_CAMERA "+JSON.stringify(m)} style={styles.overlay}><Text style={styles.text}>{`UI ${m.uiFps.toFixed(0)} FPS · ${m.frameMs.toFixed(1)}ms · slow ${m.slowFrames}\nP ${m.visibleProvinces} · A ${m.visibleArmies} · L ${m.visibleLabels}\nTick ${m.simulationMs.toFixed(1)}ms · NET ${m.networkMs.toFixed(0)}ms / ${m.networkBytes}B\n${m.preset} / ${m.geometryLod} · GPU FPS unavailable\nCache ${(m.rasterBytes/1048576).toFixed(1)} MiB · tiles ${m.rasterTiles} · cull ${m.cullCommits}\nBenchmark ticks: ${m.benchmarkTicks} · ${m.benchmarkError||'OK'}`}</Text></View>;});
export const PerformanceControls=memo(function PerformanceControls({frameRate,onFrameRate,overlay,onOverlay,adaptive,onAdaptive,running,onBenchmark}:{frameRate:FrameRate;onFrameRate:(n:FrameRate)=>void;overlay:boolean;onOverlay:(v:boolean)=>void;adaptive:boolean;onAdaptive:(v:boolean)=>void;running:boolean;onBenchmark:()=>void}){const [report,setReport]=useState('');return <View style={{gap:8}}><Text style={styles.text}>ЧАСТОТА КАМЕРЫ / DEVELOPER</Text><View style={{flexDirection:'row',gap:6}}>{(['Auto',30,60] as const).map(n=><Pressable key={n} style={styles.button} onPress={()=>onFrameRate(n)}><Text style={styles.text}>{frameRate===n?'✓ ':''}{n} FPS</Text></Pressable>)}</View><Pressable style={styles.button} onPress={()=>onAdaptive(!adaptive)}><Text style={styles.text}>Адаптивное качество: {adaptive?'Вкл':'Выкл'}</Text></Pressable><Pressable style={styles.button} onPress={()=>onOverlay(!overlay)}><Text style={styles.text}>Performance overlay: {overlay?'Вкл':'Выкл'}</Text></Pressable><Pressable disabled={running} style={styles.button} onPress={onBenchmark}><Text style={styles.text}>{running?'Benchmark выполняется…':'Performance Benchmark'}</Text></Pressable><Pressable style={styles.button} onPress={()=>{const text=reportText();setReport(text);void Share.share({message:text,title:'Dominion performance report'}).catch(()=>{});}}><Text style={styles.text}>Сохранить / поделиться отчётом</Text></Pressable>{report!==''&&<Text selectable style={styles.text}>{report}</Text>}<Text style={styles.text}>FPS показывает частоту UI callbacks, а не подтверждённые GPU frames. Отчёт можно выделить и скопировать.</Text></View>;});
const styles=StyleSheet.create({overlay:{position:'absolute',right:64,top:64,backgroundColor:'#101820ee',padding:8},text:{color:colors.parchment,fontSize:11},button:{minHeight:44,padding:10,justifyContent:'center',backgroundColor:colors.raised,borderRadius:tokens.radius.control}});
